# Generated by Django 5.0.6 on 2025-03-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
