# Generated by Django 5.0.6 on 2025-03-08 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentblog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='love',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_love', to=settings.AUTH_USER_MODEL),
        ),
    ]
