# Generated by Django 5.0.6 on 2025-02-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_apply_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='published_at',
        ),
    ]
