# Generated by Django 5.0.6 on 2025-02-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_apply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
