# Generated by Django 5.0.6 on 2025-03-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_job_love'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='love',
        ),
    ]
